### ISSUE TITLE
can you add this as output "domain.com is up" 

### ISSUE THREAD

**Issue by ethicalbughunter** [sindresorhus/is-up-cli#1]
Thanks for sharing your tool

**Comment by kevva** [comment]
Why?

**Comment by ethicalbughunter** [comment]
It improves readability and further eases text processing.

**Comment by sindresorhus** [comment]
I don't see how it improves readability. You already see what you typed right above it. And the eases text processing argument is moot as you should just use the exit codes, not parse the output.
